### ISSUE TITLE
Vers une stabilisation des lignes de l’encodage XML

### ISSUE THREAD

**Issue by glorieux-f** [dge-csic/xdge#11]
Sur le long terme, il serait souhaitable d’arriver à une version canonique du XML du dge où les numéros de ligne ne changent plus trop. Il est exclus que par exemple l’application s’appuie sur les sauts de ligne, mais cela permet d’arriver à une vue confortable pour les humains, et cela garantirait que les expressions régulières s’’appliquent avec prudence sur des objets cohérents.

Cf. le commit https://github.com/dge-csic/xdge/commit/994454bdceae474cf30dd67a8eb5b52b6859559e

~~~~
      <entry type="NP" xml:id="Ἔναλος">
        <form>
          <orth type="lemma">Ἔναλος</orth>
          <gramGrp>-ου, ὁ</gramGrp>
        </form>
        <dictScrap>
          <def>Enalo</def>
        </dictScrap>
        <sense>
          <num>1</num>
          <usg>mit., fundador de Lesbos</usg>,
          <bibl xml:id="bibl726292"><author>Anticl.</author><biblScope>4</biblScope></bibl>,
          <bibl xml:id="bibl726293"><author>Myrsil.</author><biblScope>14</biblScope></bibl>,
          <bibl xml:id="bibl726294"><author>Plu.</author><biblScope>2.163b</biblScope></bibl>.
        </sense>
        <sense>
          <num>2</num>
          <usg>n. de una roca consagrada a Posidón en Lesbos</usg>,
          <bibl xml:id="bibl726295"><author>Plu.</author><biblScope>2.163d</biblScope></bibl>.
        </sense>
      </entry>
~~~~

Qu ’est-ce qui n’est pas bien segmenté ?

**Comment by thuillier-s** [comment]
Peux-tu me donner une vue d'un article avec des <cit> ?

**Comment by thuillier-s** [comment]
aie merde, des `<cit>`

**Comment by glorieux-f** [comment]
Git pull, tu as tout. Cf. historique des commits de ce WE
https://github.com/dge-csic/xdge/commits/main

**Comment by glorieux-f** [comment]
Si les lignes sont propres et n’ont rien cassé du travail que vous avez fait précédemment, ça permettra de bien suivre la dentelle pour sortir les `<ibTruc/>` et `<barbaMachin/>`.
![image](https://user-images.githubusercontent.com/5686231/190992860-bb99c2cb-6cfd-403c-a1f5-9156c6a2794b.png)

**Comment by glorieux-f** [comment]
On est OK sur l’indentation de 1 à 7 ? C’est toi qui fermes.
