### ISSUE TITLE
def/hi/xr, renvois dans une définition, pas toujours en droit ?

### ISSUE THREAD

**Issue by glorieux-f** [dge-csic/xdge#15]
xdge7
~~~~
<def>Eménidas<hi> descendientes de Eménides <xr><ref><hi rend="bold">I 1</hi></ref></xr></hi></def>
~~~~

**Comment by thuillier-s** [comment]
Il n'y a pas de raison valable pour avoir un `xr` dans une trad. de lemme. Je dénombre 4 cas de `def/hi/xr`. Dans tous les cas, encodage erroné. Le segment en `<hi>` devrait plutôt être un `<usg>` hors du `<def>` car il ne s'agit pas de complément de traduction.

**Comment by glorieux-f** [comment]
Tu peux faire ? C’est le genre d’interprétation que je ne peux pas me permettre.

**Comment by thuillier-s** [comment]
Bien sûr. J'update, corrige puis committe maintenant ?

**Comment by thuillier-s** [comment]
c'est fait

**Comment by glorieux-f** [comment]
Pourquoi tu as réouvert l’issue ? Ce n’est pas fait ?
