### ISSUE TITLE
Adopte un monstre

### ISSUE THREAD

**Issue by glorieux-f** [dge-csic/xdge#16]
Les fichiers du dge étant lourds, il serait pratique d’avoir un monstre concentrant toutes les horreurs et cas bizarres pour mettre au point css et autres visualisations.
https://github.com/dge-csic/xdge/blob/main/monstre.xml

**Comment by thuillier-s** [comment]
horreur toi-même

**Comment by glorieux-f** [comment]
Ajouté, un cas de puce suivi de `<cit>`
1 ἄᾰτος
![image](https://user-images.githubusercontent.com/5686231/191279475-afc34eab-8a50-4e7a-b799-0ba9e962b6f2.png)

**Comment by thuillier-s** [comment]
Ok, c'est un cas courant
