### ISSUE TITLE
Author Mode ? SURTOUT PAS

### ISSUE THREAD

**Issue by glorieux-f** [dge-csic/xdge#17]
À voir, ça semble joli
![image](https://user-images.githubusercontent.com/5686231/191130228-a3b8e738-f648-4a05-a5ce-fff82c6acf09.png)
Mais le code !
![image](https://user-images.githubusercontent.com/5686231/191130544-d1451f6a-9852-48d6-9834-4209ced7d525.png)

**Comment by thuillier-s** [comment]
Je ne comprends pas quel et où est le problème que tu signales.

**Comment by glorieux-f** [comment]
Quand on modifie du texte, il se sent obliger de réindenter.
J’étais en train de mettre au point une css pour le XML

**Comment by thuillier-s** [comment]
Donc, on n'utilise pas le mode author pour première visualisation ?

**Comment by glorieux-f** [comment]
Tu peux, mais tu risques d’avoir la tentation de modifier un caractère et bousculer l’indentation. Il te suffit de placer un fichier dans ton navigateur en local, comme ici en ligne
https://dge-csic.github.io/xdge/
