### ISSUE TITLE
Vue CSS dans le navigateur (local et en ligne)

### ISSUE THREAD

**Issue by glorieux-f** [dge-csic/xdge#18]
https://dge-csic.github.io/xdge/monstre.xml
Fichier XML directement lié à la CSS auteur. Base de prototype pour mettre au point la présentation.

![image](https://user-images.githubusercontent.com/5686231/191135791-5c86cec3-d2a3-4952-9570-2cb54bd09171.png)

**Comment by glorieux-f** [comment]
Bug a noter, problème avec les ponctuations de ce genre
~~~~
<bibl xml:id="bibl549478"><author>A.</author><title>A.</title><biblScope>376</biblScope></bibl>
            </cit>.
          </sense>
~~~~
Le point derrière le `<cit>` se colle mal au `</bibl>`. Ça ne manquait pas de logique, mais les navigateurs en ont une autre. Un problème à remonter le point dans l’arbre XML ?
~~~~
    </bibl>.
  </cit>
</sense
~~~~

**Comment by thuillier-s** [comment]
Ça prend forme, super !
Le point bien sûr ne fait pas partie du `cit`, mais ce n'est pas dramatique. Et les virgules, de même.
Par ailleurs, la surbrillance des `<bibl>` semble accentuer l'impression d'espacement de la ponctuation. Pour l'affichage définitif, ce sera peut-être mieux et plus léger (il y a tellement de `bibl`) sans surbrillance, avec une police bâton étroite, proche de ton choix actuel.

**Comment by glorieux-f** [comment]
D’un point de vue typographique, l’esprit html dans une liste par exemple, c’est que le séparateur fait partie de l’item
~~~~
<ul>
  <li>Item 1 ;</li>
  <li>Item final.</li>
</ul>
~~~~

**Comment by glorieux-f** [comment]
Cette référence biblio en _badge_ était un essai. Avant d’attaquer ce sujet, je vois plusieurs tâches qui peuvent te concerner. Je ne touche plus au monstre et à la css aujourd’hui (un colloque m’attend pour un résultat en ligne).

- voir dans les volumes les articles qui tombent mal et les collecter dans monstre.xml
- choisir les fontes
- corriger des fautes d’interprétation CSS, par exemple la séparation sans-serif/serif

Tu te sens à l’aise là-dessus ?

**Comment by glorieux-f** [comment]
On a vu ces points, ils sont en train de se diviser en d’autres issues, on peu fermer ce fil ?
