### ISSUE TITLE
<bibl xml:id="100040"> n’est pas un identifiant valide

### ISSUE THREAD

**Issue by glorieux-f** [dge-csic/xdge#2]
Un identifiant @xml:id doit toujours commencer par une lettre sans accent.
Ces nombres lancent des zillions d’alertes de validation dans un process XML normal. 
Cet identifiant est-il en lien avec un système d’information ? Si oui, ce système pourrait fournir un préfixe (DMic ??)

**Comment by thuillier-s** [comment]
C'est un identifiant qu'avait généré Juan au moment des créations des <bibl> sous wordperfect. Le premier numéro correspond au numéro du volume, le reste numérotent les références au fil de leur appartion, sans autre information. Les "DMic" sont des références aux entrées d'un dictionnaire de mycénien et ne sont pas du même type de référence bibliographique. Tu peux remplacer par exemple le premier numéro par une lettre : 1 par a, 2 par b, etc. ?

**Comment by glorieux-f** [comment]
OK. le mieux est sans doute alors de prefixer l’id par bibl, cela indique le type d’objet. C’est en ligne. Si OK, on peut fermer cette issue.

**Comment by glorieux-f** [comment]
Un préfixe est inséré, mais les identifiants ne seront pas uniques avant d’avoir résolu #12

**Comment by glorieux-f** [comment]
Pb compris, se règlera avec le reste du traitement des `<bibl>`
