### ISSUE TITLE
Alignements et espacements

### ISSUE THREAD

**Issue by glorieux-f** [dge-csic/xdge#20]
Enregistrer ici les progrès des alignements réussis et ratés.

**Comment by glorieux-f** [comment]
Point de départ
![image](https://user-images.githubusercontent.com/5686231/191300505-c11f265d-bf52-42c1-8051-76b952fa5b11.png)

**Comment by glorieux-f** [comment]
Indentation des emboîtements, mais problème pour les numéros sans titres.
![image](https://user-images.githubusercontent.com/5686231/191301188-a4f0f276-08ae-4d15-bd13-76018ac58c7d.png)

**Comment by glorieux-f** [comment]
Tentative de résolution de III.1
![image](https://user-images.githubusercontent.com/5686231/191301415-25532eb5-6e6c-4e6f-846e-7d3f8aca7703.png)

**Comment by thuillier-s** [comment]
ça paraît bon, comme ça

**Comment by glorieux-f** [comment]
Il y a un pb corrigé (effet de _float_) 
![image](https://user-images.githubusercontent.com/5686231/191303845-9af17598-3b7b-4e2e-9b34-88e315207781.png)

**Comment by glorieux-f** [comment]
Nouvelle proposition
![image](https://user-images.githubusercontent.com/5686231/191493005-d1f35f29-9f98-4c9a-9718-e8515fe9cef2.png)

**Comment by thuillier-s** [comment]
Vu, les séparateurs horizontaux sont une idée à creuser, mais il ne faudrait pas l'appliquer au niveau "puce-point virgule" qui est une section de nuance. Sur mon navigateur, j'ai aussi des lignes verticales:

![image](https://user-images.githubusercontent.com/88392418/191500128-c2ef8bb6-4ce3-4972-b5b3-b78c731f4a53.png)

**Comment by glorieux-f** [comment]
Oui, je viens de les rajouter. Ce qui était dur, c’était d’habiller des boîtes qui ne sont pas rectangles
~~~~
▉▉▉▉▉▉▉▉▉▉▉▉
     ▉▉▉▉▉▉▉▉▉
     ▉▉▉▉▉▉▉▉▉
     ▉▉▉▉▉▉▉▉▉
~~~~
Ce qui est trouvé est facile à retirer. Il n’y a pas de @type sur les sense[pc], c’est facile à styler après xslt en HTML, mais ici en CSS, il faudrait ajouter un attribut sur le `<sense>`.

**Comment by thuillier-s** [comment]
Ok, et pour les articles sans numérotation, on pourra aussi supprimer la ligne : 

![image](https://user-images.githubusercontent.com/88392418/191509068-7a13ca59-d1d2-4f5c-86c2-a625bfeb1d6a.png)

**Comment by glorieux-f** [comment]
Inutile de s’accrocher si c’est une mauvaise idée. C’est toi qui vois. Si des filets apportent de la lisibilité, alors oui, tu as raison.

L’idée, ce serait de styler tous les `sense[num]` ?

**Comment by thuillier-s** [comment]
Ils apportent de la lisibilité.
Oui, `sense[num]` me semble suffisant et cohérent

**Comment by glorieux-f** [comment]
Je crois que c’est fait
![image](https://user-images.githubusercontent.com/5686231/191521648-f591f46f-a2b7-4756-9a61-d6671e0b503e.png)

**Comment by thuillier-s** [comment]
On garde comme ça pour le moment. Ne fais rien de plus sur ce point.

**Comment by glorieux-f** [comment]
À noter depuis j’ai supprimer le premier trait horizontal, pour que ce soit toujours un séparateur “entre”
![image](https://user-images.githubusercontent.com/5686231/191538967-157b3990-6419-44de-90f7-45e321511fd4.png)
Tu fermes le fil à ta convenance.

**Comment by thuillier-s** [comment]
1. Filets finalement un peu redondants : l'indentation et la numérotation paraissent suffisants.
Je les ai mis en blanc dans la css (mettre en commentaire aurait été plus orthodoxe ?).
2. Il serait vraiment intéressant d'essayer de réduire l'interligne entre les cit qui se suivent. Tu peux le faire ?

**Comment by glorieux-f** [comment]
* Tu as mis une jolie petite puce.
* C’est commenté propre (allège le navigateur)
* Interlignage des <sense> cf. 
~~~~
sense {
    /* interlignage des sense, ne pas oublier d’ajuster les numéros flottants */
    line-height: 1.2rem;
}
~~~~
![image](https://user-images.githubusercontent.com/5686231/192092621-b94e9dd7-b36b-486a-a40a-b2910ede5983.png)

**Comment by thuillier-s** [comment]
Prévoir plus d'espace sous le lemme principal

**Comment by glorieux-f** [comment]
![image](https://user-images.githubusercontent.com/5686231/193032290-65e038c5-e213-4025-b503-1ab5bf959283.png)
On commence à toucher les limite de XML/CSS, on va voir ça maintenant avec XML/XSL -> HTML/CSS
