### ISSUE TITLE
affichage entry DMic

### ISSUE THREAD

**Issue by thuillier-s** [dge-csic/xdge#21]
Le contenu des`<entry type="DMic">` sans `sense` doit être affiché comme corps de l'article (comme fait pour les `entry type="xr"`

![image](https://user-images.githubusercontent.com/88392418/191531324-9b853c07-4142-40f4-a486-5f190b79d3f9.png)

**Comment by glorieux-f** [comment]
![image](https://user-images.githubusercontent.com/5686231/192392399-40fd0336-89c9-4b3b-b092-2960b8ffd8ec.png)
