### ISSUE TITLE
<entry type="dmic">

### ISSUE THREAD

**Issue by thuillier-s** [dge-csic/xdge#24]
cf. *ἈϜάτας dans le monstre :
![image](https://user-images.githubusercontent.com/88392418/192628417-33e88d45-9832-4f1c-a182-fe03030813ec.png)
Dans ces cas-là. le `bibl type="dmic"` doit apparaître comme le corps de l'article, comme pour les `entry type="xr"` et contrairement aux cas tels que [ἀλοιφή ](http://dge.cchs.csic.es/xdge/%E1%BC%80%CE%BB%CE%BF%CE%B9%CF%86%E1%BD%B5) (qui lui doit sortir du corps de l'article et s'affiche correctement)
![image](https://user-images.githubusercontent.com/88392418/192629467-2d4b919e-ba86-4f97-8070-b8c1faf8610f.png)

**Comment by glorieux-f** [comment]
![image](https://user-images.githubusercontent.com/5686231/193029003-4b97dd99-3a31-49ca-9be3-27b8f8e03096.png)
Fermable ?
