### ISSUE TITLE
<hi rend="roman"> -> <hi> ?

### ISSUE THREAD

**Issue by glorieux-f** [dge-csic/xdge#6]
Les ancêtres les plus fréquents de `<hi rend="roman">` semblent (sans ordre)
* `<quote>`
* `<title>`
* `<def>`
Cette information typographique présume la typographie des citations, titres, et définitions (italique). Ne serait-il pas plus propre de juste dire que c’est du texte en “italique dans de l’italique” ? = `<hi>`

**Comment by thuillier-s** [comment]
Je ne sais pas si j'ai compris. <hi rend="roman"> encadre un segment de texte droit dans de l'italique. Pour <quote> et <def>, ce sont des compléments ou précisions de traduction qui sont trop attachés à cette trad. pour se retrouver dans un <usg> ou <lbl> détaché. L'idée est qu'ils seront inclus dans la recherche de trad.

**Comment by thuillier-s** [comment]
Bref, on peut leur chercher un nom d'élément plus descriptif de leur contenu (sauf dans le cas de title)

**Comment by glorieux-f** [comment]
Inutile de penser au moteur de recherche de la mort qui tue que personne ne saura utiliser, commençons par assurer la typographie.
Est-ce que `<quote>` et `<def>` sont par défaut affichés en italique ?

**Comment by thuillier-s** [comment]
Oui, par défaut, en italique.
