### ISSUE TITLE
bibl / bibl, pourquoi ?

### ISSUE THREAD

**Issue by glorieux-f** [dge-csic/xdge#7]
Soit

~~~~
<bibl xml:id="700243"><bibl xml:id="700243"><author>Mosch.</author></bibl> en <bibl xml:id="700243"><author>Ath.</author><biblScope>485e</biblScope></bibl></bibl>
~~~~

Je ne connais pas Mosch., mais en quoi serait-il une référence bibliographique s’il n’existe que dans Ath. ? C’est un genre de référence bibliographique analytique ? À noter, l’identifiant est le même pour ces trois `<bibl>`. 

En ce cas un modèle canonique.

~~~~
<bibl>
 <title level="a">The Interesting story of the Children in the Wood</title>. In
<author>Victor E Neuberg</author>, <title>The Penny Histories</title>.
<publisher>OUP</publisher>
 <date>1968</date>. 
</bibl>
~~~~

Ceci semble plus juste

~~~~
<bibl xml:id="bibl700243"><author>Mosch.</author> en <author>Ath.</author><biblScope>485e</biblScope></bibl>
~~~~

Une réponse serait utile ici pour pouvoir poursuivre.

**Comment by thuillier-s** [comment]
Tu as raison

**Comment by thuillier-s** [comment]
![image](https://user-images.githubusercontent.com/88392418/191976893-82b4b383-d4bc-4666-8e42-5dc153009758.png)

S'affichera correctement quand un seul `<bibl>`, j'imagine

**Comment by glorieux-f** [comment]
Espace perdue, corrigé 
https://github.com/dge-csic/xdge/commit/d5d1a40a2e737fc7d5d7bd6ef5c5bd4997b0a6ea

**Comment by glorieux-f** [comment]
Fait, en conservant bibl/note/bibl. Ce fil peut sans doute être fermé.

**Comment by glorieux-f** [comment]
Si tu ne fermes pas, je referme, tu peux rouvrir si tu vois un pb.
